---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/english/author
  label: Authors
  create: all
  match: "**/*"
- type: directory
  path: content/english/post
  label: Posts
  create: documents
  match: "**/*"
- type: document
  path: content/english/about.md
  label: About us
- type: document
  path: content/english/opensource.md
  label: Open Source
upload_dir: config/_default/static/forestory-uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
